// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkj42VETNAfiHQvV69y9a8C3v1qgQ5UFU',
    appId: '1:526275680631:web:fccaf564031ca82d572972',
    messagingSenderId: '526275680631',
    projectId: 'portfolio-e910f',
    authDomain: 'portfolio-e910f.firebaseapp.com',
    storageBucket: 'portfolio-e910f.firebasestorage.app',
    measurementId: 'G-VL1BP56BEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLJq5pHyNDgqsHIRxNYRtEKUU0HBHHxFQ',
    appId: '1:526275680631:android:9131ef7363b9663e572972',
    messagingSenderId: '526275680631',
    projectId: 'portfolio-e910f',
    storageBucket: 'portfolio-e910f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUHxTjE-wHaf9kaZImCUhL0j9iwBhXXY',
    appId: '1:526275680631:ios:7b28dbbdf9f72da9572972',
    messagingSenderId: '526275680631',
    projectId: 'portfolio-e910f',
    storageBucket: 'portfolio-e910f.firebasestorage.app',
    iosBundleId: 'com.example.portfolioAli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGUHxTjE-wHaf9kaZImCUhL0j9iwBhXXY',
    appId: '1:526275680631:ios:7b28dbbdf9f72da9572972',
    messagingSenderId: '526275680631',
    projectId: 'portfolio-e910f',
    storageBucket: 'portfolio-e910f.firebasestorage.app',
    iosBundleId: 'com.example.portfolioAli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkj42VETNAfiHQvV69y9a8C3v1qgQ5UFU',
    appId: '1:526275680631:web:64bf0e47f2cae104572972',
    messagingSenderId: '526275680631',
    projectId: 'portfolio-e910f',
    authDomain: 'portfolio-e910f.firebaseapp.com',
    storageBucket: 'portfolio-e910f.firebasestorage.app',
    measurementId: 'G-DHG79QZXGP',
  );
}
